// <auto-generated />
using System;
using Cembjr.ControleFrota.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cembjr.ControleFrota.Data.Migrations
{
    [DbContext(typeof(ControleFrotaContext))]
    partial class ControleFrotaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cembjr.ControleFrota.Business.Entities.Atendente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdAten")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExcluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("AtenNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("AtenTele")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CFAten");
                });

            modelBuilder.Entity("Cembjr.ControleFrota.Business.Entities.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdMoto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasColumnName("MotoCnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExcluido")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("MotoNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("MotoTele")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CFMoto");
                });

            modelBuilder.Entity("Cembjr.ControleFrota.Business.Entities.Servico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdServ")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Chegada")
                        .HasColumnName("DatCheg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnName("ServDest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdAtendente")
                        .HasColumnName("IdAten")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdMotorista")
                        .HasColumnName("IdMoto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdVeiculo")
                        .HasColumnName("IdVeic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsExcluido")
                        .HasColumnType("bit");

                    b.Property<int?>("KmFinal")
                        .IsRequired()
                        .HasColumnName("ServKmFina")
                        .HasColumnType("int");

                    b.Property<int>("KmInicial")
                        .HasColumnName("ServKmInic")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnName("ServObse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Saida")
                        .HasColumnName("DatSaid")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdAtendente");

                    b.HasIndex("IdMotorista");

                    b.HasIndex("IdVeiculo");

                    b.ToTable("CFServ");
                });

            modelBuilder.Entity("Cembjr.ControleFrota.Business.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IdVeic")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExcluido")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnName("VeicMarc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnName("VeicMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnName("VeicPlac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CFVeic");
                });

            modelBuilder.Entity("Cembjr.ControleFrota.Business.Entities.Servico", b =>
                {
                    b.HasOne("Cembjr.ControleFrota.Business.Entities.Atendente", "Atendente")
                        .WithMany("Servicos")
                        .HasForeignKey("IdAtendente")
                        .IsRequired();

                    b.HasOne("Cembjr.ControleFrota.Business.Entities.Motorista", "Motorista")
                        .WithMany("Servicos")
                        .HasForeignKey("IdMotorista")
                        .IsRequired();

                    b.HasOne("Cembjr.ControleFrota.Business.Entities.Veiculo", "Veiculo")
                        .WithMany("Servicos")
                        .HasForeignKey("IdVeiculo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
